scripts: init: Add alternative oe-core build env setup
If poky is not used, check for the oe-core as an alternative.
Source oe-core build environment if oe-core repository is used.

TISDKs use oe-core instead of poky.

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>

diff --git a/scripts/init b/scripts/init
--- a/scripts/init
+++ b/scripts/init
@@ -95,7 +95,17 @@ if [ -f "${ROOTDIR}/build/conf/bblayers.conf" ] || [ -f "${ROOTDIR}/${1}/conf/bb
         done
 fi
 
-cd ${ROOTDIR}/sources/poky/
+
+# source poky/oe-core build environment script.
+# Use poky script if repository is given, otherwise fallback to oe-core script.
+if [ -e "${ROOTDIR}/sources/poky" ]; then
+	cd ${ROOTDIR}/sources/poky/
+elif [ -e "${ROOTDIR}/sources/oe-core" ]; then
+	cd ${ROOTDIR}/sources/oe-core/
+else
+	echo >&2 "poky/oe-core build environment script not found."
+	exit 1
+fi
 . ./oe-init-build-env > /dev/null
 
 ${PHYTEC_DIR}/scripts/init_bblayers.py
