scripts: init: Print proper build environment source command
Make use of a function get_init_env_dir() to print
the correct build environment source command.

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>

diff --git a/scripts/init b/scripts/init
--- a/scripts/init
+++ b/scripts/init
@@ -95,18 +95,20 @@ if [ -f "${ROOTDIR}/build/conf/bblayers.conf" ] || [ -f "${ROOTDIR}/${1}/conf/bb
         done
 fi
 
+get_init_env_dir() {
+	if [ -e "${ROOTDIR}/sources/poky" ]; then
+		echo sources/poky
+	elif [ -e "${ROOTDIR}/sources/oe-core" ]; then
+		echo sources/oe-core
+	else
+		echo >&2 "poky/oe-core build environment script not found."
+		exit 1
+	fi
+}
 
 # source poky/oe-core build environment script.
-# Use poky script if repository is given, otherwise fallback to oe-core script.
-if [ -e "${ROOTDIR}/sources/poky" ]; then
-	cd ${ROOTDIR}/sources/poky/
-elif [ -e "${ROOTDIR}/sources/oe-core" ]; then
-	cd ${ROOTDIR}/sources/oe-core/
-else
-	echo >&2 "poky/oe-core build environment script not found."
-	exit 1
-fi
-. ./oe-init-build-env > /dev/null
+cd ${ROOTDIR}/$(get_init_env_dir)
+. ${ROOTDIR}/$(get_init_env_dir)/oe-init-build-env > /dev/null
 
 ${PHYTEC_DIR}/scripts/init_bblayers.py
 ${PHYTEC_DIR}/scripts/copy_site_conf.py
@@ -136,7 +138,7 @@ echo ""
 echo "To set up your shell environment for some Yocto work, you have to type this"
 echo "command, including the 'dot':"
 echo ""
-echo "    $ . sources/poky/oe-init-build-env"
+echo "    $ . $(get_init_env_dir)/oe-init-build-env"
 echo ""
 echo ""
 container_usage
