scripts: init: Drop sources/poky fallback
The combined poky checkout was replaced by separate openembedded-core,
bitbake and meta-yocto repos, so sources/oe-core is the only build env.
Drop sources/poky fallback.

Signed-off-by: Wadim Egorov <w.egorov@phytec.de>
Signed-off-by: Martin Schwan <m.schwan@phytec.de>

diff --git a/scripts/init b/scripts/init
--- a/scripts/init
+++ b/scripts/init
@@ -95,15 +95,13 @@ fi
 get_init_env_dir() {
 	if [ -e "${ROOTDIR}/sources/oe-core" ]; then
                 echo sources/oe-core
-	elif [ -e "${ROOTDIR}/sources/poky" ]; then
-		echo sources/poky
 	else
-		echo >&2 "poky/oe-core build environment script not found."
+		echo >&2 "oe-core build environment script not found."
 		exit 1
 	fi
 }
 
-# source poky/oe-core build environment script.
+# source oe-core build environment script.
 cd ${ROOTDIR}/$(get_init_env_dir)
 . ${ROOTDIR}/$(get_init_env_dir)/oe-init-build-env > /dev/null
 
